# Generated by Django 3.1.5 on 2021-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamdeck',
            name='brightness',
            field=models.IntegerField(default=30),
        ),
    ]
