# Generated by Django 3.1.5 on 2021-01-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0002_streamdeck_default_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdeckkey',
            name='change_to_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_keys', to='streamdeck.folder'),
        ),
        migrations.AlterField(
            model_name='streamdeckkey',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streamdeck.command'),
        ),
    ]
