# Generated by Django 3.1.5 on 2021-08-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0002_auto_20210825_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStyle',
            fields=[
                ('font', models.CharField(blank=True, max_length=30)),
                ('text_size', models.IntegerField(default=14)),
                ('text_position', models.CharField(choices=[('center', 'center'), ('top', 'top'), ('bottom', 'bottom')], default='center', max_length=6)),
                ('text_color', models.CharField(default='white', max_length=20)),
                ('streamdeck_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='streamdeck.streamdeckkey')),
            ],
        ),
        migrations.RemoveField(
            model_name='streamdeckkey',
            name='font',
        ),
        migrations.RemoveField(
            model_name='streamdeckkey',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='streamdeckkey',
            name='text_position',
        ),
        migrations.RemoveField(
            model_name='streamdeckkey',
            name='text_size',
        ),
    ]
