# Generated by Django 3.1.5 on 2021-02-07 08:55

from django.db import migrations, models
import streamdeck.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0003_auto_20210128_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdeckkey',
            name='image_source',
            field=models.FileField(blank=True, null=True, upload_to=streamdeck.models.get_image_path),
        ),
    ]
