# Generated by Django 3.1.5 on 2021-01-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0003_auto_20210121_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdeckkey',
            name='change_to_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_to_change', to='streamdeck.folder'),
        ),
        migrations.AlterField(
            model_name='streamdeckkey',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streamdeck.command'),
        ),
    ]
