# Generated by Django 3.1.5 on 2021-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0004_auto_20210207_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_type',
            field=models.TextField(choices=[('SH', 'Shell'), ('HK', 'Hotkey')], default='SH', max_length=2),
        ),
    ]
