# Generated by Django 3.1.5 on 2021-09-16 15:34

from django.db import migrations, models
import streamdeck.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0004_auto_20210826_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamdeck',
            name='full_deck_image',
            field=models.FileField(blank=True, null=True, upload_to=streamdeck.models.get_image_path_streamdeck),
        ),
        migrations.AlterField(
            model_name='streamdeckkey',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='streamdeckkey',
            name='text_position',
            field=models.CharField(choices=[('center', 'center'), ('top', 'top'), ('bottom', 'bottom')], default='bottom', max_length=6),
        ),
    ]
