# Generated by Django 3.1.5 on 2021-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0005_command_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.TextField(choices=[('Shell', 'Shell'), ('Hotkey', 'Hotkey')], default='Shell'),
        ),
    ]
