# Generated by Django 3.1.5 on 2021-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0006_auto_20210222_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.TextField(choices=[('shell', 'Shell'), ('hotkey', 'Hotkey')], default='shell'),
        ),
    ]
