# Generated by Django 3.1.5 on 2021-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0007_auto_20210222_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('shell', 'Shell'), ('hotkey', 'Hotkey')], default='shell', max_length=6),
        ),
    ]
