# Generated by Django 3.1.5 on 2021-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0008_auto_20210929_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('shell', 'shell'), ('hotkey', 'hotkey'), ('stopwatch', 'stopwatch'), ('timer', 'timer'), ('write', 'write')], default='shell', max_length=9),
        ),
    ]
