# Generated by Django 3.1.5 on 2021-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0009_auto_20210224_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='active_directory',
            field=models.TextField(default='.'),
        ),
    ]
