# Generated by Django 3.1.5 on 2021-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0009_auto_20211027_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdeck',
            name='screensaver_time',
            field=models.IntegerField(default=0),
        ),
    ]
