# Generated by Django 3.1.5 on 2021-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0011_auto_20210228_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotkeys',
            name='key1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotkeys',
            name='key2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotkeys',
            name='key3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotkeys',
            name='key4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotkeys',
            name='key5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
