# Generated by Django 3.1.5 on 2021-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0012_auto_20210304_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotkeys',
            name='key1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
