# Generated by Django 3.1.5 on 2021-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0013_auto_20210304_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdeckkey',
            name='text',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
