# Generated by Django 3.1.5 on 2021-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0014_auto_20210306_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamdeckkey',
            name='timer',
            field=models.BooleanField(default=False),
        ),
    ]
