# Generated by Django 3.1.5 on 2021-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0015_streamdeckkey_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamdeckkey',
            old_name='timer',
            new_name='clock',
        ),
    ]
