# Generated by Django 3.1.5 on 2021-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0016_auto_20210307_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='intervall_time',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('shell', 'shell'), ('hotkey', 'hotkey'), ('stopwatch', 'stopwatch')], default='shell', max_length=9),
        ),
    ]
