# Generated by Django 3.1.5 on 2021-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0017_auto_20210310_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='intervall_time',
            new_name='interval_time',
        ),
    ]
