# Generated by Django 3.1.5 on 2021-03-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0018_auto_20210310_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
