# Generated by Django 3.1.5 on 2021-03-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdeck', '0019_auto_20210312_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='interval_time',
        ),
        migrations.AddField(
            model_name='command',
            name='time_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('shell', 'shell'), ('hotkey', 'hotkey'), ('stopwatch', 'stopwatch'), ('timer', 'timer')], default='shell', max_length=9),
        ),
    ]
