language: python
python:
- '3.6'
services:
- docker
jobs:
  include:
    - stage: cody style check
      script:
      - flake8
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t py-stream .
      - docker images
      - docker tag py-stream $DOCKER_USERNAME/py-stream
      - docker push $DOCKER_USERNAME/py-stream
install: pip install flake8
env:
  global:
  - secure: kbFpMMiGkoCNzCClOgrdHTs4dmkx20elVEHTsnMEnTIQzzbOVcMbSAcg9CQYnbff1886Aea1O3jjceKJddNZvWnBN4PqobKBGXWcyoRbKLVwogThIxZyZt9pvpan9PcQrxcgT3PkzBkwNTXvpfDeuiOM6I3pVm3wAwFlOQhfEhQNI10XJe8AWU3XxiBwT4o632rOc4uNSO8PbrIcnw6GNSaRyoScUC8BrCsr4rPuDIsE6UJfw9o2jCDh1voRylZ106tf0tUZInRDWYLfykvaTQA7aKjHzNAIMDOkz+JHfKi1iOuo5TnwoyYPZiniFwCc3FtdiEZzGM3vX0nGjCu2R5VV/Lzm/4V7FNtCOiZCztWg/gQl4MrNiN9C74znebcOiMuhrgJO0/nFFT3kT84hBxbfLtlPJS1rseXZb+KfsVJ1v0nfa7nhcbfXFPHJVI/tNRWfeb37WQrVbVsNNUIvl21Lf5C+N/FzUQAh0lsL5emtoKr+vNdTSKf2zb2HeDbG/qfXe8xmpc1K9a7iKkLlNGScjRgB0VNlQZv8Cc9TfASC3SksJvinc6QS1PfUjvSCnp3subG7EXrMGv/Lro4UfjXSYX5P9b/lWV5cEPz0oYl7frBv+XGWBx5ceO+NMrVfd7fHrk3fFwh280DGRqFN7a2c8dP00t7iTXELzafA4bs=
  - secure: Gpouu86jhz6o8T72vQK4TrbC3m581iS2/xrXQub+rk5QeYjYaoFiemdRA0Q2tjd6cNBwkveqCLWE8Cg2dHtbz3hBZH4s18jXeXKrSTb3UYF/xeZO0nWPudavJeMLQHjcYN/SDQZh4HtdtR3iHu+kKFy4R7/InO4cqG0UQ8VmeRDfDGn56Ei9TwzjGjOgwvMNBL2LQ9nouEnAJKBDHi45geQ5lIgHESGiIOx9YtWX0DEZ323NpqSOeYp10LOPY/D54GxKwusSPdRbM3B4rCKafqbfDHE+26e/ZShxneIVWtseAhqf+hDBY+FXcQJiiSYmlF0IuByoTrzDeFLdMKU+Z6mEuolwH9JAYt8KMU74aFJKHPwi1kv9vAOXo1YiWXxKeGrczI+YFTUEei9QFoN3lorDAN5myMYr3vBB1TRqEsxs98bc7NxSlRxPC+T8kE0xieY9xyJSoZDg+51rP6umXclOmIXhO9g06iiHiBwsn2qnrfQXllPR3gTHK34hEZTzv3czPp3NSz/oDekEI7w2BFRcgcMJFRdqAxmnQomNTs/c0gvOrcTaj0bWRT/AOs+441X7DAfCvGTYYRGeUdI09yi5NMfUw3hLlM2xJ9L0nXyfC5baNGCo3W9Wtk6sX05yPFmgbxJnOVVye+9ZTo2b/1EjA+8VOf2cYlmdtPaI7+A=
