# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stream Deck Application
email: danielrudrich@yahoo.de
description: Application with GUI for the Elgato Stream Deck
domain: "daniel-rudrich.github.io" # the subpath of your site, e.g. /blog
url: "https://daniel-rudrich.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /streamdeck-application/

# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  parse_block_html: true

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/daniel-rudrich/streamdeck-application"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true